### ISSUE TITLE
per Track Jack Output port

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#116]
Since there are no stereo loops i want to apply some stereo effects on the tracks, so i need per channel jack outputs. would be a great feature ;)

**Comment by harryhaaren** [comment]
Hi Georg, @geraldmwangi was thinking about working on a JACK output per track feature, not sure how progress is going though.. I'm not planning on working on that as I don't currently have a need for it (and externalinzing the tracks audio to JACK introduces another period of latency..)
I'm interested to hear what you're using Luppp for though :) -Harry

**Comment by geraldmwangi** [comment]
Hi George, harry. I've got per track send/returns built-in now. If you want to try it out:
go to https://github.com/geraldmwangi/openAV-Luppp,
clone the jack-send-returns branch
compile
add  "enablePerTrackSendReturns":    1 to luppp.prfs
and start luppp.

In qjackctl you see then one send and one return port per track.
I haven't put it in my master branch since I still want to add send/return volume knobs to the gui.
Gerald

**Comment by georgkrause** [comment]
@harryhaaren how i use it? well, i use a lot of synthesizers and effects, so i need stereo and some point, but its okay to have it behind the looper. but my aim is to record minimal tracks and put some effects. you should look and a band like darkside, they do it in a similar way. but at the moment my musical skills dont fit my expectations, so i dont need this right now.

@geraldmwangi great, i will try. i will give you feedback here ;)

**Comment by georgkrause** [comment]
@geraldmwangi where is this lupp.prfs file? cannot find it :o

**Comment by georgkrause** [comment]
@geraldmwangi its technically working for me, but i dont get the concept. there is a return, but if i send the output to an effect and back to the return, the original signal is mixed with the "effected". so i have double of the loudness? at the moment it seems like it would be great to send the outputs to the effects, then to a mixer and mix them there...

**Comment by geraldmwangi** [comment]
Hi georg,
It works the following way: each track has a send and a return.
when returnX of track X is *not* connected then sendX is internally routed to returnX.
That means the audio trackX gets mixed into the main mix. So if you where using luppps main out as well, thats where the dry signal comes from the main out.

But if your setup is: sendX-> fx-> returnX then only the wet signal from the fx gets mixed in.

You could just send the sendX to the external mixer and leave the main outs of luppp unconnected
Gerald

**Comment by geraldmwangi** [comment]
btw you can get me on IRC: JimsonDrift on #lad #lau on freenode.net. I'm nearly 24/7 there

**Comment by georgkrause** [comment]
@geraldmwangi i wrote you in #lad but you didnt respond. so i write here again:
i connected Send_track_0 with qjackctl to another port, but i still have the output of track1 in the master of luppp

**Comment by harryhaaren** [comment]
@georgkrause : The outputs from the track are routed internally by default - if you connect the track itself to an external JACK port, the audio routing also changes. Note this is *per track*, not global (see here [https://github.com/geraldmwangi/openAV-Luppp/commit/6f88b009f63453e6724b754c29e01c5fb116cdc0#diff-8dcc09be22bc57c797d2c37e3849b012R28])

So you should test connecting send_track_0 to an external JACK port, and check if the audio from track_0 is still routed to master. All other tracks output is still expected to go to master (feature not bug ; )

**Comment by georgkrause** [comment]
@harryhaaren 
> So you should test connecting send_track_0 to an external JACK port, and check if the audio from track_0 is still routed to master. All other tracks output is still expected to go to master (feature not bug ; )

the answer is yes, but the coded you linked to seems like i need to connect the return, the switch is at this point. another try...

**Comment by georgkrause** [comment]
okay, after checking again i think i know how its works. great! will test it in a more productive environment

**Comment by geraldmwangi** [comment]
The internal per track routing (sendX->returnX) is only  DISconnected when returnX is connected via jack to another source. When sendX is connected to another jack port it still gets routed internally to returnX

**Comment by geraldmwangi** [comment]
Btw, sorry I didn't reply. You normally have to try pinging me two three 
times : ping  JimsonDrift ('ping' is not necessary but standard on lad (?) )
And wait...
Gerald

**Comment by harryhaaren** [comment]
@georgkrause : what is the status of this issue, is there work remaining to be done, or can I close this?

**Comment by georgkrause** [comment]
done ;)
