### ISSUE TITLE
Keyboard Layouts

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#118]
I use Luppp with a german keyboard and when i want to trigger the clips i run in some trouble. i guess the problem is the hardcoded english keyboard.

the problem occurs on y/z and Shift+Number. On my keyboard it is:
1 - !
2 - "
3 - §
4 - $
5 - %
6 - &
7 - /
8 - (
9 - )

i know how to change it in the code, but i would like to request the feature to change it in the settings.

**Comment by harryhaaren** [comment]
Sorry, low priority.. things like internationalization are hard to do right, and I hope musicians don't use the keyboard... build an Arduino based MIDI controller :D 

@ALL reading this: +1 this if you would like to see this happen.

**Comment by georgkrause** [comment]
well, i own a midi controller so its not that problem for me, but in my eyes its a bug when the keyboard triggers the wrong clip...

**Comment by georgkrause** [comment]
Maybe this is related to #188

**Comment by harryhaaren** [comment]
If somebody files a PR then I'll merge, no issue there. In needs to fix the problem correctly (aka, existing keyboard language still work, and more can be added easily). Perhaps it is better to use the scan-key code (which I belive doesn't change, if the keyboard layout changes).

**Comment by harryhaaren** [comment]
PR's still welcome, closing this to clean up for now. Will re-open when a dev gets time to work on it.
