### ISSUE TITLE
Save Clip

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#121]
While there is the option to Load a Clip, it would be cool if there is a possibility to save a clip. (Right click -> save)

**Comment by harryhaaren** [comment]
Hi @georgkrause - I think that was a good feature request - implemented and tested here, please test.
On selecting an existing filename, it asks "Overwrite" - please double-check that functionality, and click cancel at wierd times to make it crash if you can :wink: 
Cheers, -Harry

**Comment by georgkrause** [comment]
seems to work after a simple first check, will proof it in productive use ;)
