### ISSUE TITLE
Track Fader 0 != Mute

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#125]
When the Fader of a Track or of the Master Section are set to 0 they still output some sound.

**Comment by harryhaaren** [comment]
I just tried to turn down master and it worked fine - is there any particular step, resizing the UI or something that reliably triggers this?

**Comment by georgkrause** [comment]
cannot reproduce it here anymore on my own, so i consider it as working. maybe it was a problem with a specific version but now i used the current master.

But there is another bug related to the fader: when they are on 0, i cannot move them anymore with the gui, but its working with a midi controller.

**Comment by harryhaaren** [comment]
Filed a new issue for mouse not responding to click/move: https://github.com/openAVproductions/openAV-Luppp/issues/137

Closing as not reproduced, but please post here if it acts wierd again, and I'll re-open and we can debug. Thanks -H

**Comment by georgkrause** [comment]
okay, have this issue again:
- play some loops
- turn master volume to full
- turn the track volumes to null
- there is still a pretty quit signal on the master

**Comment by harryhaaren** [comment]
@georgkrause thanks for the update - would you test maximixing the *tracks*, and bringing the *master* entirely down - does it suffer from the same issue? I'm asking as there are some small differences between the volume implementations and I'm curious do both need fixing. I'll get some headphones and test when I find some time.. thanks -H

**Comment by georgkrause** [comment]
i changed the title because the master fader dont have the same issue. if the master fader is at 0, everything is silent.

**Comment by harryhaaren** [comment]
Thanks for the extra info. @geraldmwangi added a dezipper filter to the master fader - which probably solves this issue. We need de-zippers on all tracks too (and all other volume controls like sends, returns etc..)

Lets solve the Tracks issue first :)

**Comment by georgkrause** [comment]
sorry, i need to reopen this issue again, but i have some more information:
i can totally turn down the tracks via gui, but when i move the fader of my apc mini to 0, there sometimes remains some sound. i tested, the apc mini sends value 0, bug i can move the fader with the mouse a little more down.

**Comment by harryhaaren** [comment]
@georgkrause so the MIDI binding setting the track volume is the problem? If you turn the GUI fader down *after* having reproduced the issue with the MIDI controller, does the GUI result in total silence again?

**Comment by georgkrause** [comment]
yes. i turn the fader with the controller down, and then i can use the mouse to mute the audio. but there is no or nearly no visible change when i move the fader with the mouse after the moving it with the controller.

**Comment by harryhaaren** [comment]
The GUI sends commands even if the fader doesn't move - moving a single px (even when fader is 100% down already) will cause a new `EventTrackVolume` to be sent to the DSP thread. 

I'm interested to see if the MIDI controller really sends 0, and where that value isn't being correctly changed to a 0.f. I'll grab a MIDI controller later and test, unless you get to it first :)

**Comment by georgkrause** [comment]
well i checked out with jack_midi_dump and there is a 0 shown. Dont know about any possible not working changing.

**Comment by georgkrause** [comment]
@harryhaaren i will update the PR Pad and the changelog tomorrow. Maybe i can also do a little test. Thanks!

**Comment by georgkrause** [comment]
its already done since you worked on this before. allright
