### ISSUE TITLE
Clips out of sync after tempo change

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#128]
I recorded some loops on 88bpm and changed the tempo to 105bpm and some clips are not played in time anymore. i guess it are the ones which are not played and the moment of the tempo change, i will do some testing and give more information.

**Comment by geraldmwangi** [comment]
yes that's I problem I've been working on. It's got to do with the fact that the playhead variable in LooperClip isn't synced correctly to the new bpm values. Stopping and starting the clips correctly offsets the playhead position in LooperClip

**Comment by harryhaaren** [comment]
This would be nice to fix, but not a show-stopper.

**Comment by georgkrause** [comment]
@geraldmwangi @harryhaaren could you please five me some information about how to debug this? just some hints, i have no idea at all.

**Comment by georgkrause** [comment]
i did some testing and the clips are in sync to each other, but not to the click/timer of luppp anymore. i am slowly getting into this...

**Comment by georgkrause** [comment]
I logged the playhead at the beginning of each bar after i recorded a one bar length clip and changed the tempo. My exception was it will be $FramesPerBar at the beginning of each bar. This would mean the clip starts _exactly_ at the beginning of a bar. But it seems like there are missing some frames for each bar.
Also, for any reason, the fpb stored in a instance of looper isnt correctly after a tempo change, which might be an issue too.

I am still not at the root of the issue, but i feel i get closer and closer. Just wanted to collect my results of todays session and would be happy about some input about if you have time, @harryhaaren @geraldmwangi.

**Comment by georgkrause** [comment]
Okay, todays sessions results:
- the wrong fpb is the reason why clips drift out of sync *among each other* (has nothing todo with loosing sync with metronome)
- the reason for the wrong fpb-value is the cast from float to int in https://github.com/openAVproductions/openAV-Luppp/blob/master/src/timemanager.cxx#L87 

For the last point: When i set bpm to 90, fpb should be 32000 but its 31999 because of the wrong rounding. Using `round` here seem to fix the issue (didn't checked it over longer time yet). I will let run luppp for some hours now to check out if the clips will still be in sync to each other. If yes, i will file a PR and then I could focus on smoothing out the gap to the metronome after changing tempo.

**Comment by georgkrause** [comment]
Okay, obviously its not enough to fix the rounding there, although it makes thinks better. but there are some BPMs that result in uneven offsets at the beginning of a clip.

So this is not fixable by changing single lines of code. As far as i can see we have two possibilitys:
1. Reset the playhead at the beginning of a clip to zero. This is possible, we can count the length of a clip in bars while recoding and have a countdown while playing. But the result would be a gap between end and start of a clip. This should be just a few samples big, but might be audible anyway. On the other side its easier to implement.
2. We could change the hole ways how the numbers are handelt. At first we should think about switching from sample-based timing to something with more resolution, red something about tick-based timing (Ardour does something alike for 6.0). This would prevent weird roundings. Another point to look at is the amount of conversions from bpm to frames and back to bpm. There are some points in the code with multiple conversions, which is not neccessary and error prone. This would result in a complete refactor of the timemanager and should be a big amount of work.

From my point of view it would be a good idea to implement option 1 at first so we could move on. The result might be not perfect, but the feature of changing tempo gets usable somehow. @harryhaaren we could talk at LAC about a refactoring of the time manager. I am willing to spend time on this, i know the code now. But before we start now doing something, there should be really careful planning.

**Comment by georgkrause** [comment]
I did some further improvments by enhancing precision of numbers in the hole chain of calculations. Nearly every calculation introduces another inaccurancy, which sums up to a big gap between two clips, at least on big changes on bpm or long clips.

Biggest problem seems to be the calculation of the playspeed in looper.cxx, since we divide two big integer values and precision is quite low (like error on the 3. or 4. digits).

**Comment by harryhaaren** [comment]
Was this issue fixed by merge of https://github.com/openAVproductions/openAV-Luppp/pull/238 ?

**Comment by georgkrause** [comment]
@sub26nico and myself did some short testing and it seems like its fixed. I will close for now and reopen if there is still something left...
