### ISSUE TITLE
Luppp Crashes when loading WAV files on Ubuntu WSL

### ISSUE THREAD

**Issue by Rootopian** [openAVproductions/openAV-Luppp#132]
I have WSL running using PulseAudio forwarding audio to localhost and Xming working.  I can load Luppp and tweak all the controls, but as soon as I try to load a WAV file, it crashes without any error info in the console.  This has happened with stereo and mono wav samples alike.  What do you recommend I do so I can post some diagnostic info?

**Comment by geraldmwangi** [comment]
Are you talking about the linux for windows subsystem? Do you have jack running under WSL?

**Comment by harryhaaren** [comment]
Hi @Rootopian , sorry for the delay, I thought I'd already responded.. :/

@gerald's questions beg to be answered, I'm curious what you're actually doing, and also why..

On a more technical note, I think the issue you're having is that Luppp cannot run UI and DSP in seperate processes, aka, it needs "instance access" of the for showing waveforms, loading files etc.. so I'm going to guess that's the cause. But please explain the details and I'll try help if I can :)

Cheers, -Harry

**Comment by harryhaaren** [comment]
@Rootopian any update?

**Comment by harryhaaren** [comment]
As no response and using PulseAudio with WSL just isn't the intended use-case for luppp, so its a un-supported cornercase. Closing.
