### ISSUE TITLE
Save Directory

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#135]
In Luppps Options file is a option to set the save directory, in which the sessions should be stored. but this does not work.

`gui->getDiskWriter()->initialize( getenv("HOME"), name );` (gui.cxx 198)

This line sets the path to the saved session to users home. In diskwriter.cxx 108ff the session is saved to the directory given by path (which is set to home)

```
if ( !gui->getNsm() )
   sessionDirStream << "/" << sessionName << ".luppp";
```

so the path is ~/$sessionName.luppp and the option is not recognized. in the last line shown above it would be possible to add the sub directory but i dont know who. @geraldmwangi wanted to look at this, so here are my notes so far.

**Comment by harryhaaren** [comment]
Sounds like a bug yes, the NSM dir should be used as the save directory, and the load should happen from the NSM save directory. When not using NSM it should just a sane default or use-specified location instead.

**Comment by harryhaaren** [comment]
Pull request in waiting on info: https://github.com/openAVproductions/openAV-Luppp/pull/136
Marking this as Waiting too

**Comment by geraldmwangi** [comment]
This can be closed since the changes are in main repo
