### ISSUE TITLE
Fader doesn't respond to mouse

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#137]
When clicked in lowest part of fader box, the fader doesn't respond. This is probably due to a bug in mouse-handling in a) the fader, b) the track. The moving-parts to get Jack inserts added to the UI moved the position of the fader downwards - which would explain why only the bottom ~50 px isn't responsive, while the rest is.

**Comment by harryhaaren** [comment]
This seems to be caused by a larger Volume widget - the lower part of the widget doesn't recieve DRAG events like the top 80% does, (drag = event type 5, while lower part gets event type 0 "no event")..

**Comment by georgkrause** [comment]
maybe this is since @geraldmwangi added some gui elements, maybe this is the fault?

**Comment by geraldmwangi** [comment]
Fixed in my lastest PR

**Comment by harryhaaren** [comment]
Fixed here, and merged: https://github.com/openAVproductions/openAV-Luppp/pull/143
Closing.
