### ISSUE TITLE
Discussion: Midi looping

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#140]
i know, the discussion i start here is pretty hard because it would be a really big work, but i want to start it anyway:

Luppp should loop midi besides of audio.

The reason for me is pretty simple, but may corresponds with my kind to make music. my aim would be to record and loop some pretty simple and minimal loops and create tension by changing the sound and, of course, start and stopp loops. Luppp is a really great piece of software for doing the latter and even the first is getting better with the per track outputs. so i can do a lot of stuff with the sound by adding some effects. But maybe we can go one step further: record midi loops, send them (eg per track) to a synthesizer and play with the settings. i would pretty much like this feature because it would open new possibilities. 

what do you think?

**Comment by Gimmeapill** [comment]
Extending to Midi sequencing was discussed a bit a while back:
https://github.com/openAVproductions/openAV-Luppp/issues/98

Doesn't seem to be on the menu for now though...

**Comment by georgkrause** [comment]
oh well. sad that this was closed, i really want to have this ;)

**Comment by georgkrause** [comment]
okay, i thought a lot about this one in the last time since i would really like to have this feature. in my opinion its pretty cool to adjust the params of a synthesizer while playing to get some effects and i like the look and feel of luppp, so i which there where the possibility to loop midi and send it to a synth without running an extra program which does not have the same nice gui like Luppp.

BUT: 
- this would need a lot of work and redesign
- there are other programs out there which can do what i want
- better to have luppp which does one thing good than two things maybe not that good

So i am closing this.
