### ISSUE TITLE
Midi Controller Shift Button

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#142]
What i want to do is: pressing a button on my controller to map all other buttons to another function.
At the moment i am doing this with a quite complex plugin construction which transposes all the messages of my APC Mini to another channel when a specific key is pressed. but this one is not pretty stable.

So i want Luppp to be able to do this on its own. dont know at the moment what would be the best way but i want this:

pressing a shift key + a clip button -> clear clip
pressing another shift key + a clip button -> overdub (not possible at the moment)
pressing a shift key + scene launch button -> stop all clips in scene
pressing a shift key and moving a fader -> adjust the effect send

**Comment by geraldmwangi** [comment]
+1

**Comment by harryhaaren** [comment]
Mappa handles this "shift" functionality. Lets close this, and focus on Mappa.
