### ISSUE TITLE
Tempo Tap Nudge Button

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#147]
When a user of Luppp jams with other people there is the possibility to sync the tempo with the tap button. This is working well but the problem is, that the user cannot set the first beat. @geraldmwangi wants to implement a nudge button which exactly do this. so you can tap the tempo and use the nudge button to set the first beat and luppp is in sync with the other musicians.

**Comment by harryhaaren** [comment]
Resetting to the 1st beat, 1st Bar is implemented as a PR here (note it is severly outdated, but may still be applicable for the next implementation of extra features): https://github.com/openAVproductions/openAV-Luppp/pull/81

**Comment by georgkrause** [comment]
@geraldmwangi wants to implement this, maybe he takes a look...

**Comment by geraldmwangi** [comment]
I picked this up in #152

**Comment by harryhaaren** [comment]
Closing this as it a duplicate, and now being tracked as part of "Refactoring of TimeManager" #152
