### ISSUE TITLE
pre Release?

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#154]
Maybe it would be a good idea to make a pre release, like beta or something. This way maybe some others test Luppp and anyone can see there will be a release soon.

**Comment by harryhaaren** [comment]
I do this un-officially, usually using IRC, and ask some trusted users to compile and do a smoke-test. Doubling the packagers work with -beta releases isn't worth it - its either understood to be stable, or its not. Current state (my understanding of anyway) is that its stable - which means after some IRC testing, I'm happy to release it.

Open to suggestions / improvements, but I do like to keep the workflow lightweight for others in the ecosystem :)

**Comment by georgkrause** [comment]
Well, i understand this and i am totally okay with that. But on the other side i think its a pretty good idea to have a time before the release without any work on the code base except fixing bugs. we dont need to tag this.
i dont know how much packagers would work on a beta package, i think there are not that much. But i understand that this can be some overhead, so i am closing this. maybe we can discuss this later on irc again.
