### ISSUE TITLE
Input Volume Slider

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#159]
I am talking about the top right input volume slider. My request would be to remove it because in my workflow it isnt usable, but maybe there are others so at first i want to ask a question. When i use Luppp i want that the recorded clip has the same volume like the instrument i play. i am doing something like that:
````
              |------------ Luppp ---------|
instrument ---|                            | 
              |----------------------------|------ monitor
````

So when i record a clip and it is played the clip has a lower volume than the live played instrument which is a problem. So i always turn the slider to the most right, the loudest, position. 

When i imagine another workflow, so the monitoring is done with luppp i would prefer to bring all instruments on the same level before luppp and adjust the monitor volume with the orange knob, but i see no reason why i should ever turn down the volume of the input signal. 

So, what workflow i cannot imagine now depends on this slider?

**Comment by harryhaaren** [comment]
In short, we shouldn't remove it for backwards compatiblity (somebody somewhere in the world might really like it being there), and with the Snd/Key/Mix featurs, there are reasons to require a gain trim on input.

Also keep in mind that the input slider can amplifly:
https://github.com/openAVproductions/openAV-Luppp/blob/master/src/jack.cxx#L631

**Comment by georgkrause** [comment]
i am okay with not removing it since it doesnt hurt me. i was just wondering if there is any use...

is the default position +/- 0db? because with this setting the clips are less loud than the instrument itself. maybe i need look in more detail on it.
