### ISSUE TITLE
Save files don't work unless ~/luppp already exists

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#163]
If the `~/luppp` directory does not exist, Luppp doesn't save a file. This needs to be fixed asap, should be a small change to ensure that the luppp/ folder exists.

**Comment by trebmuh** [comment]
Hi @harryhaaren , I think this bug as been reported by one of my (LibraZiK) user. Then, I can propose you to let me know when a fix is found, and I'll be updating the LibraZiK luppp package to check if everything is correct.

**Comment by harryhaaren** [comment]
@trebmuh - fixed now, I'll be doing a 1.1.1 release to solve this, as it is a critical bug particularly affecting new users of Luppp (as the session dir wouldn't have existed yet).

**Comment by trebmuh** [comment]
Making a 1.1.1 is a good idea.
I've been re-doing a package for LibraZiK for 1.1 + this patch. I think Nico will let you know about is soon.

**Comment by sub26nico** [comment]
Hi, I have tested this new package in LibraZiK, I tried first to save an  an empty project and anything
happened, so I recorded a loop then save the project and the ~/luppp had been created with my project.
Once the ~/luppp was created, it is possible to save an empty project.

**Comment by harryhaaren** [comment]
Hi @sub26nico, I can't reproduce the issue here - saving empty sessions, as well as normal sessions seems fine. Would you please re test?

```
# Please make sure you don't have any Luppp sessions you want to keep here!!
#rm -r luppp
./luppp
# click menu -> Save -> "dirTest"
ls ~/luppp/
# shows the project "dirTest.luppp" directory save file for me
```

Please also confirm you're testing with the fix version :D 
`[Luppp] main:63: Git: e8b15b3 fix #163; save file dir parent dir created`

Thanks, -Harry

**Comment by sub26nico** [comment]
It's OK, after #rm -r luppp (the folder was deleted in my HOME), I've opened Luppp, 
and save the empty project, naming it 'dirTest' and the luppp folder is created in my HOME. 
I don't know what happened the first time. And yes, I'm using the version with the patch, 
with the new package done by @trebmuh.

**Comment by harryhaaren** [comment]
Thanks for verifying the fix, and a shout out to Trebmuh for packaging up quickly for testing :D

**Comment by trebmuh** [comment]
and thanks to you as well to have been that responsive.
