### ISSUE TITLE
Update version number 1.1.1

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#165]

**Comment by trebmuh** [comment]
Don't forget to update the version number in the makefile https://github.com/openAVproductions/openAV-Luppp/blob/master/CMakeLists.txt
:)

**Comment by harryhaaren** [comment]
Heh, that's the exact reason I filed this issue :D

**Comment by trebmuh** [comment]
:D

**Comment by georgkrause** [comment]
@harryhaaren this is a reminder ;) i could also do the release ;)

**Comment by harryhaaren** [comment]
Bug https://github.com/openAVproductions/openAV-Luppp/issues/168 still needs fixing before release. It wasn't tagged for the release in Github, tagged it.

Also I want to fix https://github.com/openAVproductions/openAV-Luppp/issues/173 before release, improving the dial graphics.

**Comment by georgkrause** [comment]
@harryhaaren didnt know that, sorry!

**Comment by harryhaaren** [comment]
Please test the currently tagged release ( see https://github.com/openAVproductions/openAV-Luppp/issues/179 ) before announcing later in the week. Thanks!
