### ISSUE TITLE
Use native file dialog

### ISSUE THREAD

**Issue by nanu-c** [openAVproductions/openAV-Luppp#170]
At the moment luppp is using the file Chooser for opening a Session or the midi configs
http://www.fltk.org/documentation.php/doc-1.1/Fl_File_Chooser.html

can we replace this with that?
http://www.fltk.org/doc-1.3/classFl__Native__File__Chooser.html

On my screen the file Dialog is really small and I am not getting used to it.

Can we also use it for Saving a session?

**Comment by harryhaaren** [comment]
I tried implementing using the Native widget first - I forget the exact details, but it threw up some minor problems, so I used the NTK one instead. Again - time and priority. I'd welcome and merge PRs.

**Comment by nanu-c** [comment]
Okey I looked into this, replaced it by the native file chooser and nothing changed.
So I think this is not working properly in ntk. 
In general ntk is an enhanced (with cairo) but abandoned fork of fltk. Fltk now uses also cairo since 2015 like the last commit to ntk. Is it hard to switch back to the fltk?
