### ISSUE TITLE
Remember last used controller settings

### ISSUE THREAD

**Issue by nanu-c** [openAVproductions/openAV-Luppp#171]
It would be nice to not always go to the Setup-Section and Loading a generic Midi on every startup.

At least it would be possible to save this also in the session file.

**Comment by harryhaaren** [comment]
Actually there's an option in `~/.config/openAV/luppp/luppp.prfs` that allows you to name default controllers to be loaded when Luppp starts - for all sessions. IIRC, it needs a string parameter of the controller file to load:
```
"defaultControllers":   ["akai_apc40.ctlr"],
```

**Comment by nanu-c** [comment]
That's super duper and could be documented some where, because I searched it before I opend this issue.

**Comment by nanu-c** [comment]
Again thanks, that makes it aa lot easier I am happy!

**Comment by harryhaaren** [comment]
And now documented in the manual: http://openavproductions.com/doc/luppp.html#configuration
https://github.com/openAVproductions/manual/commit/2639c1afd0eb26b05d5a1a15454360c428ff5d26

Thanks for mentioning.
