### ISSUE TITLE
release-1.1.1 testing

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#179]
Some extra hands to compile/test before announcing release

**Comment by harryhaaren** [comment]
@georgkrause @coderkun @geraldmwangi if you could do a compile and basic sanity check that would be much appreciated! :)

**Comment by georgkrause** [comment]
did some quick testing. at the moment it looks like i cannot manage it to do a productive test. but the in the short quick test everything worked fine. great stuff!

**Comment by harryhaaren** [comment]
Thanks for the input @georgkrause! I'll wait a few days (out of necessity - i'm busy :) and announce release on Thurs/Friday! Thanks

**Comment by coderkun** [comment]
I will try to find some time for testing as well!

**Comment by nanu-c** [comment]
For me ubuntu 17.04 compiling, Pan and Stereo Signal is just working fine.

**Comment by coderkun** [comment]
All working fine for me (on Arch Linux using [openav-luppp-git](https://aur.archlinux.org/packages/openav-luppp-git/)).

**Comment by trebmuh** [comment]
All working here as well, it's been incorporated to the LibraZiK repo.

**Comment by harryhaaren** [comment]
Closing, new bugfix work being tracked in https://github.com/openAVproductions/openAV-Luppp/milestone/5
