### ISSUE TITLE
Metronome volume control

### ISSUE THREAD

**Issue by coderkun** [openAVproductions/openAV-Luppp#180]
The current volume of the metronome is way to high. Seriously, this is dangerous!

The metronome needs to be set to a lower volume by default. Additionally a control element for controlling the volume would be great.

**Comment by georgkrause** [comment]
@coderkun right click on the metronome button and you can set a value. But yes, it is indeed pretty loud.

**Comment by coderkun** [comment]
Thanks a lot!
