### ISSUE TITLE
Release Testing, Version Numbering etc

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#185]

**Comment by georgkrause** [comment]
Hey @harryhaaren, sorry for being away for so long, have moved away from making music because of stressfull live, maybe a big mistake? Anyway, is there anything to do for the next release i can do? some testing, documentation stuff?

**Comment by georgkrause** [comment]
@harryhaaren Since this is the only open ticket in this release, we could do an release. But do we need 1.1.2? There are some commits adressing stability of Luppp and there is the metronome volume change and the clear clips by midi features, which isn't ready for now.

Should this be an minor release before bringing ctrla to Luppp?

**Comment by georgkrause** [comment]
As far as i can see, there are PRs for all filed bugs, exept #128 and #118. @harryhaaren do you think they are release blocking?

**Comment by georgkrause** [comment]
additionally we have:
- fix wrong outputs
- fix input signal flow
- fix input volume for clip recording
- (fix timing issues)
- add some debug options
- cleanup

**Comment by georgkrause** [comment]
@harryhaaren Since there are some new features, it might be a 1.2 release? :)

**Comment by georgkrause** [comment]
I updated the changelog, @sub26nico will make an screenshot of the current version, testing is documented here: https://github.com/openAVproductions/openAV-Luppp/wiki/Release-Testing

**Comment by harryhaaren** [comment]
Agree that this has become 1.2. I've renamed and rework some issues / milestones, now https://github.com/openAVproductions/openAV-Luppp/milestone/5 is the official 1.2 release

**Comment by harryhaaren** [comment]
Merged https://github.com/openAVproductions/openAV-Luppp/pull/257, should be ready for final testing / release then!

**Comment by harryhaaren** [comment]
Fixed in https://github.com/openAVproductions/openAV-Luppp/commit/4aaaea80c271ad217496c1ff3304b1282f7fba98
