### ISSUE TITLE
Add Ctlra to Luppp

### ISSUE THREAD

**Issue by coderkun** [openAVproductions/openAV-Luppp#194]
Replace the current (MIDI) controller logic by the integration of [Ctlra](https://github.com/openAVproductions/openAV-Ctlra).

**Comment by harryhaaren** [comment]
Closing as this is covered in https://github.com/openAVproductions/openAV-Luppp/issues/146. Thanks for the input though :) -H

**Comment by harryhaaren** [comment]
Cleared milestone as Ctlra support is not merged
