### ISSUE TITLE
remove unused Code

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#200]
By getting into the Code again I found some commented stuff, eg in genericmidi.cxx. I thought i had already an PR which removed this, but anyway... Current question is: Should we keep it? Should we remove it? When is he best point for the remove? Now or later?

I could file a PR

**Comment by harryhaaren** [comment]
Cleanup is always welcome. Please use small commits, perhaps one per file or logical grouping of files, this makes review easier.

**Comment by georgkrause** [comment]
Witz #218 there is a PR targeting this issue.
