### ISSUE TITLE
Better Debugging Outputs

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#217]
At the moment i am looking at all files to remove functions which are commented out at the moment because they are not needed anymore. However, i found a lot of comments which seem to be there for debugging. Wouldnt it be better to define a "debug mode" which one could set before compiling which would activate all this debug outputs? Seems to be a lot easier and cleaner.

**Comment by coderkun** [comment]
@georgkrause, can you post an example of how it is done currently and one of how you think it would be better?

**Comment by georgkrause** [comment]
Well, there are some commented printfs in some files which seems to be there to output some debug information. 

would be nice to do something like
```if(DEBUG) printf ...```

**Comment by coderkun** [comment]
There is also `debug.hxx/cxx` which defines functions to log debug output. Shouldn’t these be used?

Except from `debug.hxx`:

    #define LUPPP_NOTE( format, args... ) luppp_debug( DEBUG_LEVEL_NOTE, NAME, __FILE__, __FUNCTION__, __LINE__, format, ## args )
    #define LUPPP_WARN( format, args... ) luppp_debug( DEBUG_LEVEL_WARN, NAME, __FILE__, __FUNCTION__, __LINE__, format, ## args )
    #define LUPPP_ERROR( format, args... ) luppp_debug( DEBUG_LEVEL_ERROR, NAME, __FILE__, __FUNCTION__, __LINE__, format, ## args )

**Comment by georgkrause** [comment]
@coderkun you are right, there are some prebuild functions for debugging but i dont know how they fit together at the moment.

**Comment by coderkun** [comment]
I would also like to know how to set the log level to get the actual log messages ;)

**Comment by harryhaaren** [comment]
The Ctlra code has a better (runtime capable) logging mechanism. It could be ported to Luppp relatively easily I think.

**Comment by georgkrause** [comment]
Is there any documentation how it works or could you point us to the implementation?

**Comment by harryhaaren** [comment]
Code is documentation, Ctlra code available here
https://github.com/openAVproductions/openAV-Ctlra/blob/master/ctlra/impl.h#L46

There's probably some improvements that can be made there, but it works well enough
