### ISSUE TITLE
Wrong track outputs

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#220]
I recorded a clip on each track and listened to the track_*_[l/r] outputs provided by jack.

normally i would assume, that on track_1_l and track_1_r i hear the output of track one. But in fact its that way:

track_1_l   track 1
track_1_r   track 2
track_2_l   track 3
track_2_r   track 4
track_3_l   track 5
track_3_r   track 6
track_4_l   track 7
track_4_r   track 8
track_5_l   track 8
track_5_r   nothing
track_6_l   nothing
track_6_r   nothing
track_7_l   nothing
track_7_r   nothing
track_8_l   nothing
track_8_r   nothing

This might be release-blocking.

**Comment by georgkrause** [comment]
tried to investigate this, but i am hardly confused by the jack.cxx. All this int o = i*2 seems to be crazy, is this really intended? looks like a hacky workaround for stereo stuff

**Comment by georgkrause** [comment]
There is a branch `trackconfusion` in my repository where @coderkun and i fixed the trackouts. But now there is another weird bug.

If i put data to return 1 l/r and return 2 l i can hear the input on the outputs of each track. this does not work for the other returns.  the sends are working as expected.

**Comment by coderkun** [comment]
I am still investigating this issue and have found one additional typo for L/R. Will report any result.

**Comment by georgkrause** [comment]
maybe related to this: the left sidechain key does not send anything when input key is enabled.

**Comment by georgkrause** [comment]
nevermind, @coderkun already fixed this last one.
