### ISSUE TITLE
zipper noise 

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#223]
When i switch the FX-Button on and off while playing something, there is a short noise. Can someone reproduce this? 

Its not audible if the track is silent at the moment. I can reproduce this by recording a note which is one bar long and then turn the send on and of while playback.

**Comment by harryhaaren** [comment]
this is known as "zipper noise" and comes from the volume value not being smoothed. Thanks for the bug report, yes this must be fixed.

**Comment by georgkrause** [comment]
is this release-blocking? wont have time for this until next week.

**Comment by harryhaaren** [comment]
Yes it'd be good to fix this in this release, given its a known bug now.

**Comment by georgkrause** [comment]
There are other known Bugs, too which we wont fix i guess. Question is, if this bug is big enough to prevent us from delivering fixes for other bugs. But thats your choice.

Since i have no idea about dsp stuff yet and am pretty focused on the midi stuff, maybe you can look at this? Could also check this out but will take some time...

**Comment by georgkrause** [comment]
There is also noise on:
- between end and start of a clip (not when starting and stopping, only when playing)
- moving FX-Knob
- turning fx on and off
- turning send on and off
- moving send knob
- moving pan knob fastly
- turning key button on and off
- moving sidechain knob

**Comment by georgkrause** [comment]
Okay, after reading the code there is already some kind of smoothing for the volume fader of the track and the master. We could apply the same approach to the knobs. @coderkun propose to do this in a function which will be called everywhere. Not sure about this one.

Another topic are the buttons, because we need to smooth the value against 0. 

Anyway, i found the same problem on:
- input volume
- input mix button
- input mix knob 
- input sidechain signal knob
- input sidechain key button
- input snd button
- input snd knob

**Comment by georgkrause** [comment]
actually i have the same problem when i move the faders of the tracks fast.

**Comment by georgkrause** [comment]
I did some testing, on higher samplerates there is still noise, on eg 44.1khz its working pretty nice. This means we need some smoothing calculation based of the samplerate...

**Comment by harryhaaren** [comment]
Is the bug ready-to-close now with the PR for smoothing controls merged? ( https://github.com/openAVproductions/openAV-Luppp/pull/243 )

**Comment by georgkrause** [comment]
yes.
