### ISSUE TITLE
App Image

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#237]
Would be great to have an AppImage of Luppp...

**Comment by georgkrause** [comment]
Obviously, meson is able to generate a "Linux binary", but not a app image. Might work as well.

https://mesonbuild.com/Creating-Linux-binaries.html

**Comment by probonopd** [comment]
Can I help to make an AppImage?

**Comment by georgkrause** [comment]
@probonopd I kind of missed your message, help would be really appreciated!

**Comment by probonopd** [comment]
Can you compile it on Ubuntu trusty or xenial? Once you have that working, I can help to turn it into an AppImage.

**Comment by georgkrause** [comment]
@probonopd I am actually working currently on a Travis CI build on Xenial. This is nearly finished and could be merged soon. So we can use this build for the App Image. Can this be build on Travis CI also?

**Comment by georgkrause** [comment]
Travis CI Build is ready here #270

**Comment by probonopd** [comment]
Cool @georgkrause thank you 👍 

Unfortunately I don't know anything about meson. Do you know how to achieve the equivalent of

````
  - ./configure --prefix=/usr
  - make -j$(nproc)
  - make install DESTDIR=$(readlink -f appdir)
````

or

````
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install
````
there?

**Comment by georgkrause** [comment]
This is probably something @harryhaaren knows, if not I need to dig into the configuration tomorrow.

But as far as I know builds with make are still possible besides meson. So the first example could work.

**Comment by probonopd** [comment]
Can you use make in your PR? 

From my experience it is much less hassle to get it to work on older LTS systems than meson (which seems to need python 3 and other very recent dependencies).

**Comment by georgkrause** [comment]
Honestly spoken I would prefer to stick with meson since this is or at least will be the official method to build Luppp. Since 14.04 will be not supported anymore in a few weeks, 16.04 is the latest LTS and building it works fine.

I will care for your wished settings.

**Comment by georgkrause** [comment]
@probonopd Done in the PR. Looks like:

```
 ~/workspace/openAV-Luppp# ls -R builddir/appdir
builddir/appdir:
usr

builddir/appdir/usr:
bin

builddir/appdir/usr/bin:
luppp
```

Is this as expected?

**Comment by probonopd** [comment]
OK, let's consider 16.04 as the oldest supported one. Thanks, that meson change looks easy enough and reasonable. 👍

**Comment by probonopd** [comment]
Seems it is not entirely working yet?

```
0.51s$ DESTDIR=./appdir ninja -C build install ; find ./appdir
ninja: Entering directory `build'
[1/4] Generating version.hxx with a custom command.
fatal: No names found, cannot describe anything.
[2/2] Installing files.
Installing luppp to ./appdir/usr/bin
find: ‘./appdir’: No such file or directory
The command "DESTDIR=./appdir ninja -C build install ; find ./appdir" exited with 1.
0.77s
```

https://travis-ci.com/probonopd/openAV-Luppp/builds/107580818#L1418

Here is my `.travis.yml`:

https://github.com/probonopd/openAV-Luppp/blob/patch-1/.travis.yml

**Comment by georgkrause** [comment]
@probonopd Is it already working? Where will the App Image be uploaded to?

**Comment by georgkrause** [comment]
`- DESTDIR=./appdir ninja -C build install ; find ./builddir/appdir`

It is in `./build/appdir`

**Comment by probonopd** [comment]
Once the build is working, it should appear on https://github.com/probonopd/openAV-Luppp/releases. Once we have tested it successfully, I will send a pull request to your repository which, in case you merge it, will be amended to your pull request automatically.

**Comment by probonopd** [comment]
Running into

```
Desktop file as first argument: "build/appdir/usr/share/applications/*.desktop"
ERROR: Desktop file in first argument does not exist!
```

Indeed, only the main binary seems to be installed but the desktop file, icon files, and any other files seem to be missing:

```
[2/2] Installing files.
Installing luppp to ./appdir/usr/bin
./build/appdir
./build/appdir/usr
./build/appdir/usr/bin
./build/appdir/usr/bin/luppp
The command "DESTDIR=./appdir ninja -C build install ; find ./build/appdir" exited with 0.
```

Can you add them please? Thanks.

**Comment by georgkrause** [comment]
> Once the build is working, it should appear on https://github.com/probonopd/openAV-Luppp/releases. Once we have tested it successfully, I will send a pull request to your repository which, in case you merge it, will be amended to your pull request automatically.

This generally sounds pretty good. What happens to builds of non-release-stuff, like can we build an AppImage of a branch to allow users to test?
Besides this, I am not the maintainer here so in the end @harryhaaren needs to decide if something gets merged.

> Can you add them please? Thanks.

This leads me to the question what is actually needed. Sure, the desktop file. There is also an `luppp.appdata.xml` which at least in archlinux belongs to the package and goes to `usr/share/appdata/luppp.appdata.xml`. I can also create `usr/share/pixmaps/luppp.png`, if needed (because you mentioned icons). But there is also a config file which usually lives in `~/.config/openAV/luppp/luppp.prfs` and gets created on startup. And there are some controller files but they might not be needed in any case.

Another question, since I cannot write to this repository and only can file a PR, should I send one to your patch so you can merge the meson changes?

This is the line which needs to be added to `build.meson` to install `luppp.desktop` to the right place:
```
install_data('./resources/metadata/luppp.desktop', install_dir: 'share/applications')
```
Feel free to copy ;)

**Comment by georgkrause** [comment]
This installs `luppp.desktop`, `luppp.appdata.xml` and `luppp.png` to the hopefully right places:

```
install_data('resources/metadata/luppp.desktop', install_dir: 'share/applications')
install_data('resources/metadata/luppp.appdata.xml', install_dir: 'share/appdata')
install_data('resources/icons/luppp.png', install_dir: 'share/pixmaps')
```

**Comment by probonopd** [comment]
> This generally sounds pretty good. What happens to builds of non-release-stuff, like can we build an AppImage of a branch to allow users to test?

It will build and upload each commit. Not just the released versions.

**Comment by probonopd** [comment]
Looks like we have an AppImage to test:
https://github.com/probonopd/openAV-Luppp/releases

Please have a look at it and let me know whether it is working as intended. Thanks!

**Comment by georgkrause** [comment]
@probonopd Had a short test, seems to work as expected. I still want to check some details... (like config file creation and controller mappings)

If you file a PR I can review and recommend the merge asap

**Comment by sub26nico** [comment]
I've tested and it seems to be ok. 'Save' et 'Open' project works nicely, config file is created and once a controller maps had been add, Luppp opens with the good configuration. Changing the bpm while playing is ok too.

**Comment by georgkrause** [comment]
@probonopd Thanks a lot! Seems to work pretty well. Just one minor thing: It seems like there is only one release with the latest build. Can we somehow have different App-Images, like for each branch? This way we can test each feature Pull Request and have always a current master build for testing. I suppose somehow we need to set the name of the release?

**Comment by probonopd** [comment]
An AppImage also gets built and uploaded for each pull request. The transfer.sh download URL is visible in the build log of a pull request.

**Comment by georgkrause** [comment]
Alright, this should work. I thought it might be possible to have releases like `continous-master` and `continous-testing`. But its not needed...

**Comment by georgkrause** [comment]
@harryhaaren This still needs to get activated on Travis which require admin rights (So I can't do this)

**Comment by harryhaaren** [comment]
Done, and seems to be working with this test PR : https://github.com/openAVproductions/openAV-Luppp/pull/273

**Comment by georgkrause** [comment]
@harryhaaren You need to setup a Github Access Token to allow the upload of the artifacts into Github Releases. Description here: https://github.com/probonopd/uploadtool#usage

**Comment by harryhaaren** [comment]
@georgkrause OK Done now, the token is in place. How do we test it?

**Comment by georgkrause** [comment]
I do. ;)

**Comment by georgkrause** [comment]
@harryhaaren I restarted the release job, so this would upload the App Image for 1.2.1.
BTW: I am on IRC if you wanna talk ;)

**Comment by georgkrause** [comment]
As you can see here, it works:  https://github.com/openAVproductions/openAV-Luppp/releases/tag/release-1.2.1
