### ISSUE TITLE
Fix clip starting from beginning in the middle of a bar

### ISSUE THREAD

**Issue by coderkun** [openAVproductions/openAV-Luppp#242]
Testing the master branch (commit 4328296), I experience a strange issue: Some clips/loops randomly abord and start from beginning. This seems to always happen on a beat but sometimes on “1” and sometimes on any other beat. Like if the loop would be too short and not filling the full bar–which is not the case, of course.

I cannot tell how this happened or how to reproduce it but was able to record a short [video](https://cloud.suruatoel.xyz/s/cybonKipwBf9Axi) (unfortunately without audio) in which it happens multiple times:

00:06 – Track 4
00:08 – Track 2
00:22 – Track 1
00:26 – Track 4

Has anyone else seen this before? Maybe it was only this one session? I will test again with a new session …

**Comment by georgkrause** [comment]
My fault, will fix asap

**Comment by georgkrause** [comment]
Please try: b0f4d8b

**Comment by coderkun** [comment]
@georgkrause, with your fix applied I was not able to reproduce the issue anymore. So from testing it appears that this commit fixes it (did not look at the code though).
