### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by mixalakis** [openAVproductions/openAV-Luppp#254]

**Comment by georgkrause** [comment]
you need help, @mixalakis?

**Comment by mixalakis** [comment]
yes , i install luppp from software manager , but i cant open it
then i try to open it from terminal , and then ,....

 $ luppp
[Luppp] main:63: Git:
[Luppp] Gui:470: Loaded preferences
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping
unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping
unlock
jack_get_sample_rate called with a NULL cl


some things about my pc

$ cat /etc/*-release

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
cat: /etc/upstream-release: Is a directory

**Comment by georgkrause** [comment]
@mixalakis This seems like you have no jack running, which is needed. Please use something like qjackctl to start it before launching luppp. 

If you want further help, you can join our Matrix-Channel: https://riot.im/app/#/room/#openav:matrix.org

**Comment by harryhaaren** [comment]
@mixalakis - when you posted this issue it was also "closed" straigh away (meaning fixed) so I presumed you fixed the issue yourself. It seems that's not the case, so I'll re-open this so we can discuss things and fix whatever problem you're having.

**Comment by harryhaaren** [comment]
Closing issue, assuming you got your issue resolved. Please post here @mixalakis if you still have issues, we can try debug/help.
