### ISSUE TITLE
Riot Phone Call

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#256]
Hello @harryhaaren @coderkun @vale981 @sub26nico and all others!

I would like to organize a little phone conference on Riot. The main reason is, i am courious how this works :D Also we could discuss some stuff, how to implement some features or other things, as you wish.

This is just an idea and I would like to hear your thoughts. Do you think this is helpful/nice? Or a wast of time? Let me know and have a nice time!

**Comment by sub26nico** [comment]
Nice idea, I'm curious to see how it works. Not sure my English is good enough, 
but it could be funny :-).

**Comment by coderkun** [comment]
I would also be interested in testing audio chat via Matrix/Riot. Would be good to have a rough agenda beforehand though.

**Comment by georgkrause** [comment]
@sub26nico don't worry about language, we will manage it :) I am not the best english speaker, too. But somehow it works :D

@coderkun I am up to talk about anything, only smalltalk to learn to know each other or discussion about features / their implementations? It would be also possible to work on the documentation together... What do you have in mind?

**Comment by harryhaaren** [comment]
Timing might be hard - and what is the priority? Aka, if its between spending time on final Luppp release fixes or chatting on riot..?

**Comment by georgkrause** [comment]
@harryhaaren priority is up to you, maybe everyone can bring up a topic to discuss and after that you can decide if you want or need to participate or not.

**Comment by georgkrause** [comment]
Here is my proposal: Lets have a Riot Phone Meeting next week, one evening. For me, everything is free at the moment, so choose a date.

Topics:
- Smalltalk :)
- Look at manual to see what needs to be updated
- Discuss #239 to get this done soon

Since this is our first try and I expect some technical things to be solved, this should be enough for the beginning.

**Comment by coderkun** [comment]
“Evening” means around 20:00 UTC+2?

**Comment by vale981** [comment]
Geez the manual.

On 27 July 2018 14:19:05 CEST, Georg Krause <notifications@github.com> wrote:
>Here is my proposal: Lets have a Riot Phone Meeting next week, one
>evening. For me, everything is free at the moment, so choose a date.
>
>Topics:
>- Smalltalk :)
>- Look at manual to see what needs to be updated
>- Discuss #239 to get this done soon
>
>Since this is our first try and I expect some technical things to be
>solved, this should be enough for the beginning. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openAVproductions/openAV-Luppp/issues/256#issuecomment-408402624

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by georgkrause** [comment]
@coderkun yes, something like that. Sadly, I am not free tomorrow anymore, but any other day will work for me.

**Comment by sub26nico** [comment]
I'll be on tour this week and  be back next tuesday.

**Comment by georgkrause** [comment]
We will wait for you to have as much people as possible ;)

**Comment by georgkrause** [comment]
Now @sub26nico is back, lets fix a date?

**Comment by sub26nico** [comment]
I'm free this week's evenings except saturday.

**Comment by coderkun** [comment]
Friday would work for me.

**Comment by georgkrause** [comment]
This weekend will not work for me, if not tomorrow maybe next week?

**Comment by sub26nico** [comment]
ok for me, tomorrow or next week.

**Comment by georgkrause** [comment]
@sub26nico i wrote this yesterday, i can make it possible this evening or one in the next week

**Comment by sub26nico** [comment]
ok for today or later

**Comment by georgkrause** [comment]
Lets fix Wednesday next week, 15th of August. Will 9pm UTC+2 work for you?

**Comment by coderkun** [comment]
Okay, August 15, 21:00 UTC+2.

**Comment by sub26nico** [comment]
ok for me

**Comment by harryhaaren** [comment]
Thanks guys, was nice to chat, we can consider doing another one in the near-ish future if we feel that its useful to chat once in a while :) I'll close this issue now to cleanup the issue-tracker.
