### ISSUE TITLE
MIDI Map Play button

### ISSUE THREAD

**Issue by harryhaaren** [openAVproductions/openAV-Luppp#261]
As reported by Claude via email, the option to MIDI-map the play/stop button would be useful for various live-performance situations. `More precisely, I would like to play loops as part of backing track, together with and a real drummer playing with a click. That's why I need the loop to be launched instantaneously. `

Just noting this publicly here, and in future if a dev wants to take it on or investigate it, then there's an issue to file work against here.

**Comment by harryhaaren** [comment]
@georgkrause @coderkun If you have time to test, please try adding the following `.ctlr` file contents to an existing mapping, and test all works as expected: https://github.com/openAVproductions/openAV-Luppp/commit/f909f1d9fb76d23983642a7d330c8dcfff147bac#diff-08754f0870229da008de9dee88e3755fR6. Currently the notes are mid-C (midi 60) for stop, and 61 (C#) for start again.

**Comment by coderkun** [comment]
The functionality itself works fine, I can start and stop Luppp’s transport with two buttons on my controller (AKAI APC mini).

The only issue I noticed is that the play/stop button on the UI does not change its label:
When I stop the transport by clicking on the start/stop button on the UI, the button changes its label from “start” to “stop”. It does not do so when I stop the transport by the controller. Vice versa for starting the transport.

**Comment by harryhaaren** [comment]
@coderkun if you have time, a quick re-test would be appreciated, it seems to work fine here now :)

**Comment by coderkun** [comment]
Works well now, @harryhaaren.

**Comment by georgkrause** [comment]
@harryhaaren whats the state here?

**Comment by harryhaaren** [comment]
This is committed to master already, just never closed. Closing now.
