### ISSUE TITLE
Add manual tempo typing to manual

### ISSUE THREAD

**Issue by unfa** [openAVproductions/openAV-Luppp#264]
I've exported some loops that were made at 115 BPM, and I wanted to set that tempo.

it took me quite a while, because I couldn't simply type it in, I had to move the tempo knob, but it only refreshes once a bar, which makes it very clunky to use.

I'd appreciate at least some immediate feedback on what the current Tempo knob position is (a hint text somewhere?).

Plus I'd love a way to (for example) double click on the knob and be able to type in a number.

**Comment by georgkrause** [comment]
@unfa Please try right click on the Tap-Button.

**Comment by harryhaaren** [comment]
And thanks @georgkrause for implementing this "right click and type" feature in https://github.com/openAVproductions/openAV-Luppp/pull/206! I'll rename this to add this feature to the manual (it doesn't look like its there now: http://openavproductions.com/doc/luppp.html#master-section)

**Comment by georgkrause** [comment]
@sub26nico this is done, right?

**Comment by sub26nico** [comment]
yes, but pull request isn't merged yet.

**Comment by harryhaaren** [comment]
Which pull request @sub26nico? I'm not aware of anything outstanding here..

**Comment by sub26nico** [comment]
@harryhaaren , in OpenAv-manual repo.
