### ISSUE TITLE
Can't find the program version number anywhere

### ISSUE THREAD

**Issue by unfa** [openAVproductions/openAV-Luppp#266]
I've tried checking what version of Luppp am I running, and I've tried these:

```
man luppp
luppp -v
luppp --version
luppp -h
luppp --help
```

None worked.

I also tried finding some version information within the program (I expected a Help menu or something) - nothing.

I finally checked the version in Synaptic.

**Comment by harryhaaren** [comment]
Does running it from a terminal not print it out?
https://github.com/openAVproductions/openAV-Luppp/blob/master/src/main.cxx#L63

**Comment by georgkrause** [comment]
Actually it would be really nice to have `luppp --version` to print it out. should not be a big problem and would make it easier to check.

**Comment by georgkrause** [comment]
@unfa what do you expect from the noted `luppp -h` or `luppp --help` to be printed? I implemented `luppp --version` and `luppp -v` to print the currently running version of Luppp. Please test if you have time, feedback really welcome ;)

**Comment by trebmuh** [comment]
This has be done here: https://github.com/openAVproductions/openAV-Luppp/pull/268
@unfa if that is fine for you, you can probably close this issue.

**Comment by georgkrause** [comment]
@unfa I will close this for now, but would be happy to implement some useful help information. Just ping me what you want to see there.
