### ISSUE TITLE
Add "fallback" to vcs_target in meson config

### ISSUE THREAD

**Issue by mprt** [openAVproductions/openAV-Luppp#267]
Hi, 
I'm using an older version of meson (0.40.1).

according to https://mesonbuild.com/Release-notes-for-0-41-0.html, the "fallback" keyword for vcs_tag became optional in version 0.41, therefore meson build fails.
Please add the "fallback" keyword to enable compatibility with oder meson versions.

**Comment by harryhaaren** [comment]
Hi, thanks for reporting - I don't have any older Meson installs so didn't find this. I'll push a fix once I'm at the development machine. Thanks, -Harry

**Comment by georgkrause** [comment]
I looked into this, pretty easy to do. @harryhaaren What should we use as fallback version? 1.0.0? Current release version (we would need to update manually)? Or something like "Could not read version number" (It seems pretty unlikely to happen)?

locally already changed, I will merge request this after discussion
