### ISSUE TITLE
Release 1.2.1 to support Linux Release Day

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#271]
A bunch of devs decided to have regular releases to increase the attention for Linux Audio Software or Open Source Audio Software.
I think this is a really good idea and we should support this. Currently we have some minor changes in the master branch which could justify a point release. Maybe also the App Image or the Looperclip Redesign can make it into the release?

The question is, if thats possible at all. @sub26nico @coderkun can you maybe jump in for some tests until than?

**Comment by georgkrause** [comment]
https://dpaste.de/kYeV

**Comment by sub26nico** [comment]
@georgkrause , I try to test it as soon as possible.

**Comment by sub26nico** [comment]
Done (as reported in the issues). AppImage and Looperclip Redesign seems to be ok.

**Comment by georgkrause** [comment]
@sub26nico thanks :)

**Comment by georgkrause** [comment]
Will be out today, therefore closing this
