### ISSUE TITLE
UX: Add a 'settings' button near the LUPPP logo

### ISSUE THREAD

**Issue by viktorsmari** [openAVproductions/openAV-Luppp#287]
### Problem
As a new user, I did not know that clicking the logo would do anything. So I thought it was not possible to Save / Load or even go to the Setup.

### Suggestion
In order to improve the UI, I suggest that there would be a 'Settings' button, or maybe something like a cogwheel icon. Could be next to the LUPPP logo on the left, or all the way to the right, above the Master section.

Related to #72

This software is brilliant btw!

**Comment by georgkrause** [comment]
@viktorsmari I am happy you like Luppp. This is indeed a nice idea for an improvement. Thanks for the suggestion.

Please don't expect this to be implemented soon, currently nobody is working on Luppp actively.
