### ISSUE TITLE
Thoughts on Luppp crossplatform/windows porting branch

### ISSUE THREAD

**Issue by Ashrakk** [openAVproductions/openAV-Luppp#307]
Hello everyone, Since this software is only available on Linux i wonder if anyone could be interested in making Luppp crossplatform or to make windows porting in their free time
Would it be easier to make it windows compatible in C++ or making a java version from scratch?

**Comment by harryhaaren** [comment]
Luppp is relatively portable; the DSP code is all OS agnostic. The UI is currently built in NTK, which is no longer maintained, and hence not a good fit.

I strongly recommend *against* writing music software in Java, it is not real-time safe*, so can/will cause glitches live on stage. (*.. unless you want to argue about JVM version with RT-safe GC etc, which I'd prefer not spend time arguing about).

Closing this as its been inactive a long time - feel free to post in future if there is interest.
