### ISSUE TITLE
git://git.tuxfamily.org/gitroot/non/fltk.git mentioned in README is dead, please replace the NTK dependency with a working one

### ISSUE THREAD

**Issue by yurivict** [openAVproductions/openAV-Luppp#317]

**Comment by moonshaadow** [comment]
Same here.
Can't build without ntk and can't find a way to get ntk

**Comment by fafaman** [comment]
Also for me. still looking for a source for this...

**Comment by yurivict** [comment]
@fafaman Here is a new fork: https://git.kx.studio/non/ntk with the latesrt tarball here: https://git.kx.studio/non/ntk/archive/v1.3.1001.tar.gz

**Comment by fafaman** [comment]
Thanks! On the way I wish to cite intriguing news from non author https://non.tuxfamily.org/wiki/2021-02-07%20Linux%20Audio%20is%20Dead as I love Linux audio and wish it is kept as healthy as possible as time goes.

**Comment by yurivict** [comment]
I think reports of Linux Audio death have been greatly exaggerated.
