### ISSUE TITLE
README update for dependency installation

### ISSUE THREAD

**Issue by WMRamadan** [openAVproductions/openAV-Luppp#319]
The README has no installation instructions for dependencies while also most available instructions are outdated.

Issue running into problems with NTK dependencies both cmake and meson report NTK not found although instructions were followed to install NTK from website https://www.netlabtoolkit.org/install-ntk-developer/

Solution:
Update README with proper dependency installation at least for Linux platform

**Comment by harryhaaren** [comment]
Hi, the Install section shows exactly what to do? https://github.com/openAVproductions/openAV-Luppp#install

In order to have any installed software picked up by Pkg-Config, it is required to install system-wide or adjust `PKG_CONFIG_PATH` (this is not Luppp specific, just general sw-dev practice on Linux).

For future readers, the NTK code is available from multiple places:
```
NTK  ( git clone git://git.tuxfamily.org/gitroot/non/fltk.git ntk
    or git clone https://git.kx.studio/non/ntk )
```

**Comment by harryhaaren** [comment]
Also, the "NTK" you've linked there is not the same NTK that is mentioned in the Luppp install instructions.

**Comment by WMRamadan** [comment]
> Hi, the Install section shows exactly what to do? https://github.com/openAVproductions/openAV-Luppp#install
> 
> In order to have any installed software picked up by Pkg-Config, it is required to install system-wide or adjust `PKG_CONFIG_PATH` (this is not Luppp specific, just general sw-dev practice on Linux).
> 
> For future readers, the NTK code is available from multiple places:
> 
> ```
> NTK  ( git clone git://git.tuxfamily.org/gitroot/non/fltk.git ntk
>     or git clone https://git.kx.studio/non/ntk )
> ```

I have managed to follow the travis.yml CI build file to get my build correctly.
Yes, I have also realized the new NTK library link mentioned.

**Comment by harryhaaren** [comment]
OK, thanks for reporting back! I'll mark this as closed.
