### ISSUE TITLE
Output bindings for grid:launch_scene not working

### ISSUE THREAD

**Issue by Vampouille** [openAVproductions/openAV-Luppp#78]
I try to light up one led when scene 1 is launched. 

In order to switch on this led Launchpad need to receive note On 8 Velocity 63 (channel 1)

Note on 24 for scene 2 (same velocity)
Note on 40 for scene 3
Note on 56 for scene 4
...

When I launch a scene : the first (note on 8) led ligh up . The same led is light up for any scene.

Here is color code used by pad :

{
        "action": "grid:clip_state",
        "status": 144,
        "data": 0,
        "track": 0,
        "scene": 0,
        "state": {
            "empty": 0,
            "stopped": 46,
            "playing": 60,
            "recording": 15,
            "queueStopped": 45,
            "queuePlaying": 28,
            "queueRecording": 13
        }
    }

Here is my mapping for scene led :

{
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 8,
      "scene"  : 0
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 25,
      "scene"  : 1
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 41,
      "scene"  : 2
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 56,
      "scene"  : 3
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 72,
      "scene"  : 4
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 88,
      "scene"  : 5
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 104,
      "scene"  : 6
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 120,
      "scene"  : 7
    },

**Comment by georgkrause** [comment]
On my APC Mini are 8 Buttons i used for launching scenes, the last 3 Buttons light up when i cklick them to launch the scene, but dont turn off when i choose another scene. Is this the same like discribed here?

**Comment by georgkrause** [comment]
spammed here a little with commits, but @Vampouille this commit should fix one of your issues. the velocity issue needs some more work.

**Comment by Vampouille** [comment]
Feel free to close this issue

**Comment by georgkrause** [comment]
@Vampouille well i wanted to luck into the velocity problem today, if it is merged we can close this here. did you tested my patch?

**Comment by Vampouille** [comment]
> did you tested my patch?

no, sorry but I stop using Lupp and create a new soft from scratch. In this soft (SuperBoucle) I handle velocity with a special value of -1 : if velocity is not 0 or 127, I replace it with -1 to indicate that this controller have variable velocity. https://github.com/Vampouille/superboucle/blob/master/learn.py#L282

**Comment by georgkrause** [comment]
@Vampouille why dont you contribute to luppp?

i guess its pretty easy to add a velocity value to the .ctrl file and send this if its there, if not set it to 127

**Comment by Vampouille** [comment]
> @Vampouille why dont you contribute to luppp?

Because it use c++ and I found synchronization issue during testing : after some time samples get out of sync.

**Comment by georgkrause** [comment]
@Vampouille okay, are you willing test this with your launchpad anyway, when i contribute a fix for the velocity problem? if not, i wont try to fix it because i dont and have launchpad and are not able to test.

**Comment by Vampouille** [comment]
I can test with my launchpad if you want, but the launchpad does not send variable velocity based on real user velocity. But launchpad react on velocity for color.
@georgkrause tell me when and what to test.

**Comment by georgkrause** [comment]
@Vampouille if i got your issue from the beginning of this thread right, you wanted to configure the color of the scene launch buttons on your launchpad with the velocity, right? that does not depend on wheather the launchpad is sending different velocities or not.

**Comment by Vampouille** [comment]
> @Vampouille if i got your issue from the beginning of this thread right, you wanted to configure the color of the scene launch buttons on your launchpad with the velocity, right?

yes

**Comment by georgkrause** [comment]
@Vampouille please try this one: https://github.com/georgkrause/openAV-Luppp/tree/issue78
add
`"color": %i,`
to your ctrl output binding to set the velocity which is send (which should set the color of the button). if there is a problem, please tell me. if everything works @harryhaaren could simply merge it, which closes this issue automatically.

**Comment by georgkrause** [comment]
@Vampouille did you tested?

**Comment by Vampouille** [comment]
> @Vampouille did you tested?

no, I will try to test it this week

**Comment by Vampouille** [comment]
I try to test with your branch 'issue78' but no MIDI message come from luppp. Can you explain or/and document how to trigger midi messages ? Maybe I need an output bindings block ?

Here is my conf : 

```json
{
   "name":"pad",
   "author":"me",
   "link":"",
   "inputBindings":[
      {

      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":8,
         "scene":0,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":41,
         "scene":2,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":56,
         "scene":3,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":72,
         "scene":4,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":88,
         "scene":5,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":104,
         "scene":6,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":120,
         "scene":7,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":40,
         "scene":2,
         "color":100
      },
      {

      },
      {
         "action":"grid:event",
         "status":144,
         "data":1,
         "track":1,
         "scene":0,
         "color":18
      }
   ]
}
```

**Comment by georgkrause** [comment]
yes, you really need a output binding block.

try:

```
{
   "name":"pad",
   "author":"me",
   "link":"",
   "inputBindings":[
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":8,
         "scene":0,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":41,
         "scene":2,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":56,
         "scene":3,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":72,
         "scene":4,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":88,
         "scene":5,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":104,
         "scene":6,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":120,
         "scene":7,
         "color":100
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":40,
         "scene":2,
         "color":100
      }
   ],
   "outputBindings": [
	{
         "action":"grid:event",
         "status":144,
         "data":1,
         "track":1,
         "scene":0,
         "color":18
      }
   ]
}
```

**Comment by Vampouille** [comment]
ok, I will try with this device configuration

**Comment by Vampouille** [comment]
I try with `outputbindings` I still have no midi message. Here is my device config : 
https://gist.github.com/Vampouille/595f8d52c4bf075950e40fafe266c719

**Comment by georgkrause** [comment]
yes, there are some errors, sorry i didnt fixed them in the previos version. this ctrl file is tested and works as expected in my case. plase try again!

```
{
   "name":"pad",
   "author":"me",
   "link":"",
   "inputBindings":[
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":8,
         "scene":0
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":41,
         "scene":2
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":56,
         "scene":3
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":72,
         "scene":4
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":88,
         "scene":5
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":104,
         "scene":6
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":120,
         "scene":7
      },
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":40,
         "scene":2
      }
   ],
   "outputBindings":[
      {
         "action":"grid:launch_scene",
         "status":144,
         "data":1,
         "scene":0,
         "color":18
      },
{
         "action":"grid:launch_scene",
         "status":144,
         "data":1,
         "scene":1,
         "color":18
      },
{
         "action":"grid:launch_scene",
         "status":144,
         "data":1,
         "scene":2,
         "color":18
      },
{
         "action":"grid:launch_scene",
         "status":144,
         "data":1,
         "scene":3,
         "color":18
      },
{
         "action":"grid:launch_scene",
         "status":144,
         "data":1,
         "scene":4,
         "color":18
      },
{
         "action":"grid:launch_scene",
         "status":144,
         "data":1,
         "scene":5,
         "color":18
      },
{
         "action":"grid:launch_scene",
         "status":144,
         "data":1,
         "scene":6,
         "color":18
      },
{
         "action":"grid:launch_scene",
         "status":144,
         "data":1,
         "scene":7,
         "color":18
      }
   ]
}
```

please notice: the color element only works for grid:launch_scene output binding. the color of a grid:event button is set by the state of the scene, so it does not make sense to set the color here.

**Comment by harryhaaren** [comment]
I expect this issue was fixed by https://github.com/openAVproductions/openAV-Luppp/commit/2cb998366c14bf8a8d42cd8533717e489c0c1fba. If there's anybody listening here, please test with latest master and report back? Cheers!

**Comment by georgkrause** [comment]
because i cannot get my handy on a launchpad and there is no answer from @Vampouille i will close this. Feel free to reopen again with more information.

**Comment by Ackkym** [comment]
Hi all, i finally found this thread, trying to configure lights support with my launchpad S through Luppp.

Actually, i am able to light up scene button with outputbinding, but i'm not able to change the color of the buttons even with the "color" parameter that is proposed here.

Also i'm unable to light up each track button, and it would be lovely to change the color for playing, recording, and other status.

Don't know if somebody gonna read my msg, 3 years after the last comment on this thread.


I'd like to thank the developers of Luppp cause you made a very nice software (even if it need update), it's already usefull and i enjoy playing music with it.
THX

**Comment by harryhaaren** [comment]
HEy @Ackkym, thanks for writing the above - always good to hear somebody is making use of Luppp!

If there's a bug/issue that we can improve on the LaunchpadS `.ctlr` file, please file a PR and we can check? I don't have the hardware, so I literally _cannot_ test things. Have to trust folks like yourself and @wvengen who contribute `.ctlr` files!

Please do open a new issue or PR to discuss for that hw? Cheers, -Harry

**Comment by Ackkym** [comment]
Hi,

thx for your answer.

I already used the github forum to post issues and ideas/request i have 
in order to improve luppp. But its already a very good software to play 
music with, so thx to you.

I finally made it works witht my lauchpad so no need to open a new 
issue.

Cheers.

Le 08.06.2021 22:05, Harry van Haaren a écrit :

> HEy @Ackkym [1], thanks for writing the above - always good to hear 
> somebody is making use of Luppp!
> 
> If there's a bug/issue that we can improve on the LaunchpadS .ctlr 
> file, please file a PR and we can check? I don't have the hardware, so 
> I literally _cannot_ test things. Have to trust folks like yourself and 
> @wvengen [2] who contribute .ctlr files!
> 
> Please do open a new issue or PR to discuss for that hw? Cheers, -Harry
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].



Links:
------
[1] https://github.com/Ackkym
[2] https://github.com/wvengen
[3] 
https://github.com/openAVproductions/openAV-Luppp/issues/78#issuecomment-857080793
[4]

**Comment by vvatelot** [comment]
Thank you for the tips!
I found out how to configure output bindings with this issue for my launchpad mini :slightly_smiling_face: 

I made a gist here for people who would like to use Luppp with a launchpad mini: https://gist.github.com/vvatelot/283995926d389975f27ccc5f91562377
